const SUPABASE_URL = 'https://puvsirrwregusqhkixdz.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_VnbXzkbyEZizn4GGTAFxiQ_BeiGw27W';
const supabaseClient = window.supabase.createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
window.supabaseClient = supabaseClient;
(async function(){
 async function loadHomepage(){const {data,error}=await supabaseClient.from('site_settings').select('content').eq('id','homepage').maybeSingle();if(error)throw error;return data?.content||{}}
 const setText=(s,v)=>{const e=document.querySelector(s);if(e)e.textContent=v??''};
 function applyPublic(c){const b=c.brand||{},h=c.hero||{};setText('.logo b',b.name);setText('.logo small',b.city);if(Array.isArray(c.nav))document.querySelectorAll('nav a').forEach((a,i)=>{if(c.nav[i])a.textContent=c.nav[i]});if(b.logoImage)document.querySelectorAll('.logo-mark').forEach(el=>{el.innerHTML='<img src="'+String(b.logoImage).replace(/["<>]/g,'')+'" alt="Darul Uloom Muhammadia logo">';el.classList.add('has-image')});setText('.hero .eyebrow',h.eyebrow);const title=document.querySelector('.hero h1');if(title){title.textContent='';title.append(document.createTextNode((h.heading||'')+' '));const sp=document.createElement('span');sp.textContent=h.highlight||'';title.append(sp)}setText('.hero-copy p',h.description);setText('.hero .actions .btn:not(.outline)',h.button);setText('.hero .actions .btn.outline',h.secondary);setText('.hero-card strong',h.cardTitle);setText('.hero-card span',h.cardSubtitle);setText('#about .eyebrow',c.about?.eyebrow);setText('#about h2',c.about?.heading);setText('#about .section-head p',c.about?.description);setText('#madrasa .eyebrow',c.madrasa?.eyebrow);setText('#madrasa h2',c.madrasa?.heading);setText('#school .eyebrow',c.school?.eyebrow);setText('#school h2',c.school?.heading);setText('#school .split>div:first-child p',c.school?.description);setText('#leadership .eyebrow',c.leadership?.eyebrow);setText('#leadership h2',c.leadership?.heading);setText('#admissions .eyebrow',c.admissions?.eyebrow);setText('#admissions h2',c.admissions?.heading);setText('#admissions .admission p',c.admissions?.description);setText('#admissions .notice',c.admissions?.notice);setText('#admissions .btn',c.admissions?.button);setText('#contact .eyebrow',c.contact?.eyebrow);setText('#contact h2',c.contact?.heading);const cp=document.querySelectorAll('#contact .contact>div:first-child p');if(cp[0])cp[0].textContent=b.address||'';if(cp[1])cp[1].innerHTML='<b>'+String(b.phone||'').replace(/[<>]/g,'')+'</b>';if(cp[2])cp[2].textContent=b.email||'';window.__siteContent=c}
 async function publicRefresh(){try{applyPublic(await loadHomepage())}catch(e){console.warn('Public CMS refresh failed:',e)}}
 const isHomePage=location.pathname.endsWith('/')||location.pathname.endsWith('/index.html'),isAdminPage=new URLSearchParams(location.search).get('admin')==='1';
 function loadInfoCards(){if(!isHomePage||document.getElementById('info-cards-script'))return;const s=document.createElement('script');s.id='info-cards-script';s.src='info-cards.js?v=20260818-2';s.defer=true;document.body.appendChild(s)}
 function loadGalleryUploadFix(){if(!isAdminPage||document.getElementById('gallery-upload-fix-script'))return;const s=document.createElement('script');s.id='gallery-upload-fix-script';s.src='gallery-upload-fix.js?v=20260817-1';s.defer=true;document.head.appendChild(s)}
 const start=()=>{if(isHomePage){publicRefresh();loadInfoCards()}loadGalleryUploadFix()};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
(function(){const isHome=location.pathname.endsWith('/')||location.pathname.endsWith('/index.html');if(!isHome)return;const load=()=>{if(document.getElementById('hero-slider-runtime'))return;const s=document.createElement('script');s.id='hero-slider-runtime';s.src='hero-slider-runtime.js?v=20260817-2';s.defer=true;document.body.appendChild(s)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load()})();
(function(){function addButton(){const p=location.pathname;if(!/admin\\.html$|management\\.html$/.test(p))return;if(document.getElementById('private-student-management-link'))return;const a=document.createElement('a');a.id='private-student-management-link';a.href='student-management.html';a.textContent='👨‍🎓 Students & Teachers';a.style.cssText='display:inline-flex;align-items:center;justify-content:center;padding:11px 14px;border-radius:9px;background:#176b3a;color:#fff;text-decoration:none;font-weight:800;margin:4px';document.querySelectorAll('.head div:last-child,.tabs').forEach(x=>x.appendChild(a.cloneNode(true)));if(!document.querySelector('#private-student-management-link')){a.style.position='fixed';a.style.right='18px';a.style.bottom='18px';a.style.zIndex='9999';document.body.appendChild(a)}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addButton,{once:true});else addButton()})();
(function(){if(!location.pathname.endsWith('student-management.html'))return;const load=()=>{if(document.getElementById('student-card-ui-fix'))return;const s=document.createElement('script');s.id='student-card-ui-fix';s.src='student-card-ui-fix.js?v=20260817-4';s.defer=false;document.body.appendChild(s)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load()})();
(function(){function addFinance(){if(!/admin\\.html$|management\\.html$|student-management\\.html$/.test(location.pathname))return;if(document.getElementById('private-finance-link'))return;const a=document.createElement('a');a.id='private-finance-link';a.href='finance.html';a.textContent='💰 Madrasa Finance';a.style.cssText='display:inline-flex;align-items:center;justify-content:center;padding:11px 14px;border-radius:9px;background:#0d47a1;color:#fff;text-decoration:none;font-weight:800;margin:4px';document.querySelectorAll('.head div:last-child,.top-actions').forEach(x=>x.appendChild(a.cloneNode(true)));}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addFinance,{once:true});else addFinance()})();
(function(){if(!location.pathname.endsWith('website-editor.html'))return;const load=()=>{if(document.getElementById('info-cards-editor-script'))return;const s=document.createElement('script');s.id='info-cards-editor-script';s.src='info-cards.js?v=20260818-3';s.defer=true;document.body.appendChild(s)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load,{once:true});else load()})();
(function(){
 function addCardEditorLinks(){
   if(!/admin\\.html$|management\\.html$|student-management\\.html$/.test(location.pathname))return;
   if(document.getElementById('student-card-editor-link'))return;
   const a=document.createElement('a');a.id='student-card-editor-link';a.href='student-card-editor.html';a.textContent='🪪 Edit Student Card';a.style.cssText='display:inline-flex;align-items:center;justify-content:center;padding:11px 14px;border-radius:9px;background:#6a1b9a;color:#fff;text-decoration:none;font-weight:800;margin:4px';
   document.querySelectorAll('.head div:last-child,.top-actions,.toolbar-actions').forEach(x=>x.appendChild(a.cloneNode(true)));
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addCardEditorLinks,{once:true});else addCardEditorLinks();
})();
