(()=>{
const esc=s=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m]));
const clean=s=>String(s??'').replace(/[\"<>]/g,'');
const clone=o=>JSON.parse(JSON.stringify(o||{}));
const slug=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const set=(o,p,v)=>{const a=p.split('.');let x=o;for(let i=0;i<a.length-1;i++){x[a[i]]=x[a[i]]||{};x=x[a[i]]}x[a[a.length-1]]=v};
const get=(o,p,d='')=>p.split('.').reduce((x,k)=>x==null?undefined:x[k],o)??d;
async function load(){const {data,error}=await supabaseClient.from('site_settings').select('content').eq('id','homepage').maybeSingle();if(error)throw error;return data?.content||{}}
function logoUrl(c){return c?.brand?.logoImage||''}
function applyLogo(c){const u=logoUrl(c);document.querySelectorAll('.logo-mark,.hero-card .crescent').forEach(el=>{if(u){el.innerHTML='<img src="'+clean(u)+'" alt="Darul Uloom Muhammadia logo">';el.classList.add('has-image')}else{el.textContent='D';el.classList.remove('has-image')}});let f=document.querySelector('link[rel="icon"]');if(!f){f=document.createElement('link');f.rel='icon';document.head.appendChild(f)}if(u)f.href=u}
function applyHero(c){const hero=document.querySelector('.hero');if(!hero)return;const u=c?.brand?.heroImage||'';hero.style.backgroundImage=u?'linear-gradient(90deg,rgba(3,15,35,.90) 0%,rgba(3,15,35,.68) 48%,rgba(3,15,35,.34) 100%),url("'+clean(u)+'")':'';hero.style.backgroundSize=u?'cover':'';hero.style.backgroundPosition=u?'center center':'';hero.style.backgroundRepeat='no-repeat';const p=document.querySelector('.hero-pattern');if(p)p.style.opacity=u?'.035':'.08'}
function applyLeadership(c){const items=c?.leadership?.items||[];document.querySelectorAll('#leadership .leaders article').forEach((el,i)=>{const x=items[i];if(!x)return;const photo=x[3]||'';el.innerHTML=photo?'<img class="final-leader-photo" src="'+clean(photo)+'" alt="'+esc(x[1])+'"><h3>'+esc(x[1])+'</h3><p>'+esc(x[2])+'</p>':'<div class="avatar">'+esc(x[0]||'')+'</div><h3>'+esc(x[1])+'</h3><p>'+esc(x[2])+'</p>'})}
function applyGallery(c){const g=c?.gallery||{},el=document.querySelector('.gallery');if(!el)return;const items=g.items||['Campus','Students','Events','Activities'];const media=g.media||{};const desc=g.descriptions||[];el.classList.add('final-gallery');el.innerHTML=items.map((name,i)=>{const list=Array.isArray(media['gallery-'+i])?media['gallery-'+i]:(Array.isArray(media[slug(name)])?media[slug(name)]:[]);const body=list.length?list.map(m=>m.type==='video'?'<figure><video src="'+clean(m.url)+'" controls preload="metadata" playsinline></video><figcaption>'+esc(m.name||'Video')+'</figcaption></figure>':'<figure><img src="'+clean(m.url)+'" alt="'+esc(name)+'" loading="lazy"><figcaption>'+esc(m.name||name)+'</figcaption></figure>').join(''):'<div class="final-empty">No photos or videos published yet.</div>';return '<article class="final-gallery-card"><button type="button" aria-expanded="false">'+esc(name)+' <span>+</span></button><div class="final-gallery-details" hidden><p>'+esc(desc[i]||'')+'</p><div class="final-media">'+body+'</div></div></article>'}).join('');el.querySelectorAll('.final-gallery-card>button').forEach(b=>b.onclick=()=>{const d=b.nextElementSibling;const open=!d.hidden;d.hidden=open;b.setAttribute('aria-expanded',String(!open));b.querySelector('span').textContent=open?'+':'−'})}
function applyLocation(c){const contact=document.querySelector('#contact .contact');if(!contact)return;const loc=c?.location||{};let box=document.getElementById('final-location');if(!box){box=document.createElement('div');box.id='final-location';box.className='final-location';contact.appendChild(box)}if(loc.show===false){box.hidden=true;return}box.hidden=false;let html='<strong>📍 Madrasa Location</strong><div>'+esc(loc.address||c?.brand?.address||'')+'</div>';if(loc.mapsUrl)html+='<a class="btn" target="_blank" rel="noopener" href="'+clean(loc.mapsUrl)+'">Open in Google Maps</a>';if(loc.lat&&loc.lng)html+='<iframe loading="lazy" title="Darul Uloom Muhammadia location" src="https://www.google.com/maps?q='+encodeURIComponent(loc.lat+','+loc.lng)+'&output=embed"></iframe>';box.innerHTML=html}
function styles(){if(document.getElementById('final-cms-css'))return;const s=document.createElement('style');s.id='final-cms-css';s.textContent=`.logo-mark.has-image,.hero-card .crescent.has-image{display:flex;align-items:center;justify-content:center;overflow:hidden}.logo-mark.has-image img{width:100%;height:100%;object-fit:contain;border-radius:10px;display:block}.hero-card .crescent.has-image{font-size:0}.hero-card .crescent.has-image img{width:86px;height:86px;object-fit:contain;border-radius:14px}.final-leader-photo{width:90px;height:90px;object-fit:cover;border-radius:50%;display:block;margin:auto}.final-gallery{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px!important}.final-gallery-card{background:#fff;border:1px solid #dfe8f3;border-radius:16px;padding:12px;box-shadow:0 8px 25px rgba(10,45,90,.04)}.final-gallery-card>button{width:100%;border:0;background:#071b3a;color:#fff;border-radius:10px;padding:14px;font-weight:800;text-align:left;display:flex;justify-content:space-between;cursor:pointer}.final-gallery-details{padding-top:10px}.final-gallery-details>p{color:#65748b;margin:0 0 10px}.final-media{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.final-media figure{margin:0;overflow:hidden;border-radius:10px;background:#071b3a}.final-media img,.final-media video{width:100%;height:220px;object-fit:cover;display:block}.final-media figcaption{color:#fff;font-size:11px;padding:8px}.final-empty{padding:25px;text-align:center;background:#eef4fb;color:#65748b;border-radius:10px}.final-location{margin-top:20px;padding:20px;border:1px solid #dfe8f3;border-radius:16px;background:#f7faff}.final-location strong{display:block;font-size:19px;color:#071b3a;margin-bottom:5px}.final-location .btn{display:inline-block;margin-top:10px}.final-location iframe{width:100%;height:300px;border:0;border-radius:12px;margin-top:12px}@media(max-width:700px){.final-gallery,.final-media{grid-template-columns:1fr}}`;
document.head.appendChild(s)}
function publicApply(c){if(!document.querySelector('.hero'))return;styles();applyLogo(c);applyHero(c);applyLeadership(c);applyGallery(c);applyLocation(c);window.__finalCmsContent=c}
async function upload(file,folder){if(!file)return '';const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,'-');const path=folder+'/'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'-'+safe;const {error}=await supabaseClient.storage.from('site-media').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return supabaseClient.storage.from('site-media').getPublicUrl(path).data.publicUrl}
function addAdminFields(){if(new URLSearchParams(location.search).get('admin')!=='1')return;const tabs=document.querySelector('.ale-tabs'),forms=document.getElementById('ale-forms');if(!tabs||!forms)return;styles();
if(!tabs.querySelector('[data-tab="location"]')){const b=document.createElement('button');b.type='button';b.dataset.tab='location';b.textContent='Location';tabs.insertBefore(b,tabs.querySelector('[data-tab="leadership"]')||null);const s=document.createElement('section');s.dataset.section='location';s.className='ale-section';s.innerHTML='<div class="ale-media"><h3>📍 Live Location</h3><div class="ale-field"><label>Address</label><input data-path="location.address"></div><div class="ale-field"><label>Google Maps Link</label><input data-path="location.mapsUrl" placeholder="Paste Google Maps share link"></div><div class="ale-field"><label>Latitude</label><input data-path="location.lat" placeholder="24.xxxx"></div><div class="ale-field"><label>Longitude</label><input data-path="location.lng" placeholder="67.xxxx"></div><div class="ale-field"><label>Show Publicly</label><select data-path="location.show"><option value="true">Yes</option><option value="false">No</option></select></div></div>';forms.appendChild(s);b.onclick=()=>{tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));forms.querySelectorAll('.ale-section').forEach(x=>x.classList.remove('active'));b.classList.add('active');s.classList.add('active')}}
const lead=forms.querySelector('[data-section="leadership"]');if(lead&&!lead.querySelector('#final-leader-media')){const box=document.createElement('div');box.id='final-leader-media';box.className='ale-media';box.innerHTML='<h3>Leadership Photos</h3><div class="ale-field"><label>Founder Photo</label><input id="final-leader-0" type="file" accept="image/*"><input data-path="leadership.items.0.3" type="hidden"></div><div class="ale-field"><label>Principal Photo</label><input id="final-leader-1" type="file" accept="image/*"><input data-path="leadership.items.1.3" type="hidden"></div><small>Upload photos here. They will be published with the leadership cards.</small>';lead.appendChild(box)}
const save=document.getElementById('ale-save');if(save&&!save.dataset.finalReplaced){const fresh=save.cloneNode(true);save.replaceWith(fresh);fresh.dataset.finalReplaced='1';fresh.onclick=async()=>{try{fresh.disabled=true;fresh.textContent='Saving & Publishing…';const c=clone(window.__finalCmsContent||await load());document.querySelectorAll('#ale-forms [data-path]').forEach(el=>set(c,el.dataset.path,el.value));c.location=c.location||{};c.gallery=c.gallery||{};c.gallery.items=c.gallery.items||['Campus','Students','Events','Activities'];c.gallery.descriptions=c.gallery.descriptions||[];c.gallery.media=c.gallery.media||{};const logo=document.getElementById('ale-logo')?.files?.[0];const hero=document.getElementById('ale-hero')?.files?.[0];if(logo)c.brand.logoImage=await upload(logo,'branding/logo');if(hero)c.brand.heroImage=await upload(hero,'branding/hero');for(let i=0;i<4;i++){const files=[...(document.querySelector(`[data-gallery-files="${i}"]`)?.files||[])];const key='gallery-'+i;const old=Array.isArray(c.gallery.media[key])?c.gallery.media[key]:[];for(const f of files)old.push({type:f.type.startsWith('video/')?'video':'image',url:await upload(f,'gallery/'+key),name:f.name});c.gallery.media[key]=old}c.leadership=c.leadership||{};c.leadership.items=c.leadership.items||[];for(let i=0;i<2;i++){const f=document.getElementById('final-leader-'+i)?.files?.[0];if(f){c.leadership.items[i]=c.leadership.items[i]||['','','',''];c.leadership.items[i][3]=await upload(f,'leadership')}}const {data:{user}}=await supabaseClient.auth.getUser();if(!user)throw new Error('Admin session expired. Please login again.');const {error}=await supabaseClient.from('site_settings').upsert({id:'homepage',content:c,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'id'});if(error)throw error;window.__finalCmsContent=c;if(window.__applySiteContent)window.__applySiteContent(c);publicApply(c);const m=document.getElementById('ale-msg');if(m){m.textContent='All website changes saved and published successfully.';m.className='ale-msg ok'}fresh.textContent='Save & Publish';fresh.disabled=false}catch(e){console.error(e);const m=document.getElementById('ale-msg');if(m){m.textContent=e.message||'Save failed';m.className='ale-msg bad'}fresh.textContent='Save & Publish';fresh.disabled=false}}}}
}
async function init(){try{const c=await load();publicApply(c);if(new URLSearchParams(location.search).get('admin')==='1'){let n=0;const timer=setInterval(()=>{addAdminFields();n++;if(n>120)clearInterval(timer)},250)}}catch(e){console.warn('Final CMS load failed',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
