(()=>{
function render(){
 const g=document.querySelector('#gallery .gallery'); const c=window.__siteContent?.gallery;
 if(!g||!c)return;
 const items=Array.isArray(c.items)?c.items:['Campus','Students','Events','Activities'];
 const media=c.media||{};
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
 const filesFor=(name,i)=>{const key=name.toLowerCase().replace(/[^a-z0-9]+/g,'-');const out=[];[media[key],media['gallery-'+i],media['gallery-'+(i+1)]].forEach(a=>{if(Array.isArray(a))a.forEach(x=>{if(x?.url&&!out.some(y=>y.url===x.url))out.push(x)})});return out};
 g.innerHTML=items.map((name,i)=>{const files=filesFor(name,i);const preview=files[0];const cover=preview?(preview.type==='video'?`<video src="${esc(preview.url)}" muted playsinline preload="metadata"></video>`:`<img src="${esc(preview.url)}" alt="${esc(name)}" loading="lazy">`):'<div class="gallery-card-placeholder">📷</div>';return `<button class="gallery-category-card" type="button" data-gallery-index="${i}"><span class="gallery-category-media">${cover}</span><span class="gallery-category-title">${esc(name)}</span><span class="gallery-category-count">${files.length} ${files.length===1?'file':'files'}</span></button>`}).join('');
 g.querySelectorAll('.gallery-category-card').forEach(card=>card.addEventListener('click',()=>open(iFrom(card),items,filesFor(items[iFrom(card)],iFrom(card)))));
 function iFrom(card){return Number(card.dataset.galleryIndex)}
 function open(i,names,files){let old=document.getElementById('gallery-media-modal');if(old)old.remove();const title=names[i]||'Gallery';const modal=document.createElement('div');modal.id='gallery-media-modal';modal.innerHTML=`<div class="gallery-modal-backdrop"></div><div class="gallery-modal"><button class="gallery-modal-close" aria-label="Close">×</button><h3>${esc(title)}</h3><div class="gallery-modal-grid">${files.length?files.map(m=>m.type==='video'?`<video src="${esc(m.url)}" controls preload="metadata"></video>`:`<img src="${esc(m.url)}" alt="${esc(title)}" loading="lazy">`).join(''):'<p>No photos or videos have been uploaded yet.</p>'}</div></div>`;document.body.appendChild(modal);const close=()=>modal.remove();modal.querySelector('.gallery-modal-close').onclick=close;modal.querySelector('.gallery-modal-backdrop').onclick=close}
}
const style=document.createElement('style');style.textContent='.gallery-category-card{display:block;width:100%;padding:0;border:0;overflow:hidden;border-radius:16px;background:#071b3a;color:#fff;text-align:left;cursor:pointer;box-shadow:0 10px 28px rgba(0,0,0,.14);transition:transform .2s,box-shadow .2s}.gallery-category-card:hover{transform:translateY(-3px);box-shadow:0 14px 32px rgba(0,0,0,.2)}.gallery-category-media{display:block;width:100%;height:220px;background:#e9eef5}.gallery-category-media img,.gallery-category-media video{width:100%;height:100%;object-fit:cover;display:block}.gallery-card-placeholder{height:100%;display:grid;place-items:center;font-size:42px;color:#718096}.gallery-category-title,.gallery-category-count{display:block;padding:11px 14px 0}.gallery-category-title{font-weight:800;font-size:17px}.gallery-category-count{padding-top:4px;padding-bottom:12px;font-size:12px;opacity:.75}.gallery-modal-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.72)}#gallery-media-modal{position:fixed;inset:0;z-index:999999;display:grid;place-items:center;padding:20px}.gallery-modal{position:relative;width:min(920px,94vw);max-height:90vh;overflow:auto;background:#fff;border-radius:18px;padding:20px;color:#13233b}.gallery-modal h3{margin:0 40px 16px 0}.gallery-modal-close{position:absolute;right:12px;top:10px;border:0;background:#eef2f7;border-radius:50%;width:36px;height:36px;font-size:24px;cursor:pointer}.gallery-modal-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.gallery-modal-grid img,.gallery-modal-grid video{width:100%;height:240px;object-fit:cover;border-radius:12px;background:#071b3a}.gallery-modal-grid p{color:#667085}';document.head.appendChild(style);
const wait=()=>{if(window.__siteContent)render();else setTimeout(wait,250)};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait);else wait();window.addEventListener('site-content-updated',render);
})();
