(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const slug=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const getMedia=(gallery,i,name)=>{const media=gallery?.media||{};for(const key of [`gallery-${i}`,slug(name),name])if(Array.isArray(media[key]))return media[key];return []};
function render(c){const g=document.querySelector('.gallery');if(!g)return;const gallery=c?.gallery||{};const items=Array.isArray(gallery.items)&&gallery.items.length?gallery.items:['Campus','Students','Events','Activities'];const descriptions=gallery.descriptions||{};g.innerHTML=items.map((name,i)=>{const list=getMedia(gallery,i,name);const desc=Array.isArray(descriptions)?descriptions[i]:(descriptions?.[i]??'');const mediaHtml=list.length?list.map(m=>m.type==='video'?`<figure class="gallery-media-item"><video src="${esc(m.url)}" controls preload="metadata" playsinline></video><figcaption>${esc(m.name||'Video')}</figcaption></figure>`:`<figure class="gallery-media-item"><img src="${esc(m.url)}" alt="${esc(name)}" loading="lazy"><figcaption>${esc(m.name||name)}</figcaption></figure>`).join(''):`<div class="gallery-empty">No media uploaded yet.</div>`;return `<article class="gallery-category"><button type="button" class="gallery-category-title" aria-expanded="false">${esc(name)} <span>＋</span></button><div class="gallery-details"><p>${esc(desc)}</p><div class="gallery-media">${mediaHtml}</div></div></article>`}).join('');let s=document.getElementById('gallery-cms-style');if(!s){s=document.createElement('style');s.id='gallery-cms-style';document.head.appendChild(s)}s.textContent=`.gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px!important}.gallery-category{background:#f5f8fc;border:1px solid #dfe8f3;border-radius:16px;padding:12px;box-shadow:0 8px 25px rgba(7,27,58,.06)}.gallery-category-title{width:100%;border:0;background:#071b3a;color:#fff;border-radius:10px;padding:14px;font-weight:800;font-size:16px;cursor:pointer;text-align:left;display:flex;justify-content:space-between;align-items:center}.gallery-details{display:none;padding:12px 2px 2px}.gallery-category.open .gallery-details{display:block}.gallery-details p{color:#65748b;margin:4px 0 12px}.gallery-media{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.gallery-media-item{margin:0;overflow:hidden;border-radius:10px;background:#071b3a}.gallery-media-item img,.gallery-media-item video{display:block;width:100%;height:180px;object-fit:cover;background:#071b3a}.gallery-media-item figcaption{padding:7px 8px;color:#fff;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.gallery-empty{min-height:120px;display:grid;place-items:center;color:#65748b;font-size:12px;background:#eef4fb;border-radius:10px}.gallery-category.open .gallery-category-title span{transform:rotate(45deg)}@media(max-width:700px){.gallery{grid-template-columns:1fr!important}.gallery-media{grid-template-columns:1fr}.gallery-media-item img,.gallery-media-item video{height:220px}}`;
g.querySelectorAll('.gallery-category-title').forEach(b=>b.onclick=()=>{const card=b.closest('.gallery-category');const open=card.classList.toggle('open');b.setAttribute('aria-expanded',open?'true':'false')})}
function wire(){const previous=window.__applySiteContent;if(typeof previous!=='function'){setTimeout(wire,100);return}if(previous.__galleryWrapped)return;const wrapped=function(c){previous(c);render(c)};wrapped.__galleryWrapped=true;window.__applySiteContent=wrapped;if(window.__siteContent)render(window.__siteContent)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire);else wire();
})();
