(()=>{
'use strict';
const defaults=[
{icon:'📖',title:'نصابِ تعلیم',body:'یہاں نصابِ تعلیم، درجات اور متعلقہ تعلیمی معلومات درج کی جائیں گی۔'},
{icon:'▣',title:'تعلیمی شعبہ جات',body:'یہاں جامعہ کے مختلف تعلیمی شعبہ جات کی تفصیل درج کی جائے گی۔'},
{icon:'◈',title:'شعبہ جات',body:'یہاں جامعہ کے مختلف شعبہ جات اور ان کی بنیادی معلومات درج کی جائیں گی۔'},
{icon:'⌂',title:'ادارہ و انتظامی معلومات',body:'یہاں ادارے، انتظامیہ اور متعلقہ معلومات درج کی جائیں گی۔'},
{icon:'⌁',title:'منصوبے',body:'یہاں جاری اور آئندہ منصوبوں کی معلومات درج کی جائیں گی۔'},
{icon:'☷',title:'قواعد و ضوابط',body:'یہاں طلبہ اور زائرین کے لیے ضروری قواعد و ضوابط درج کیے جائیں گے۔'},
{icon:'▤',title:'نوٹس بورڈ',body:'اہم اعلانات، تازہ نوٹس اور انتظامیہ کی ضروری اطلاعات یہاں دکھائی جائیں گی۔'},
{icon:'🤝',title:'طریقہ تعاون',body:'ادارے کے ساتھ تعاون، عطیات اور دیگر معاونت کے طریقہ کار کی معلومات یہاں درج کی جائیں گی.'}
];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const copy=o=>JSON.parse(JSON.stringify(o||{}));
async function read(){const {data,error}=await supabaseClient.from('site_settings').select('content').eq('id','homepage').maybeSingle();if(error)throw error;return data?.content||{}}
function items(c){const a=Array.isArray(c.infoCards)?c.infoCards:[];return defaults.map((d,i)=>{const x=a[i]||{};return {icon:String(x.icon??d.icon),title:String(x.title??d.title),body:String(x.body??d.body)}})}
function css(){if(document.getElementById('info-cards-css'))return;const s=document.createElement('style');s.id='info-cards-css';s.textContent=`
.info-cards-section{background:linear-gradient(180deg,#f7fbff,#eef5fb);padding:52px 0 58px}.info-cards-head{text-align:center;margin-bottom:28px}.info-cards-head h2{color:#071b3a}.info-cards-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.info-card{min-height:205px;border:1px solid #dbe7f3;border-radius:18px;background:linear-gradient(145deg,#071b3a,#0b3764);color:#fff;padding:28px 18px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;cursor:pointer;box-shadow:0 14px 34px rgba(7,27,58,.12);transition:transform .2s,box-shadow .2s,background .2s}.info-card:hover{transform:translateY(-4px);box-shadow:0 20px 42px rgba(7,27,58,.2);background:linear-gradient(145deg,#0b3764,#0d4f86)}.info-card-icon{width:64px;height:64px;border-radius:16px;display:grid;place-items:center;background:rgba(255,255,255,.12);font-size:34px;margin-bottom:18px;color:#dceeff}.info-card-title{font-family:serif;font-size:24px;line-height:1.5;font-weight:700}.info-card-more{font-size:12px;color:#b9d7f2;margin-top:9px}.info-card-modal{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;padding:20px}.info-card-modal.open{display:flex}.info-card-backdrop{position:absolute;inset:0;background:rgba(2,14,32,.7);backdrop-filter:blur(4px)}.info-card-dialog{position:relative;width:min(680px,94vw);max-height:82vh;overflow:auto;background:#fff;border-radius:22px;padding:34px;box-shadow:0 30px 90px rgba(0,0,0,.3);text-align:right}.info-card-close{position:absolute;left:16px;top:12px;border:0;background:#edf4fb;color:#071b3a;border-radius:50%;width:38px;height:38px;font-size:25px;cursor:pointer}.info-modal-icon{width:66px;height:66px;border-radius:16px;background:#071b3a;color:#fff;display:grid;place-items:center;font-size:34px;margin-bottom:16px}.info-card-dialog h3{font-family:serif;font-size:32px;color:#071b3a;margin:0 0 14px}.info-modal-body{font-family:serif;font-size:20px;line-height:2;color:#42536a;white-space:pre-line}@media(max-width:900px){.info-cards-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.info-cards-grid{grid-template-columns:1fr}.info-card{min-height:170px}.info-card-dialog{padding:26px 20px}.info-card-dialog h3{font-size:27px}.info-modal-body{font-size:18px}}`;document.head.appendChild(s)}
let modal=null;
function show(x){if(!modal)return;modal.querySelector('.info-modal-icon').textContent=x.icon||'•';modal.querySelector('h3').textContent=x.title||'معلومات';modal.querySelector('.info-modal-body').textContent=x.body||'';modal.classList.add('open')}
function render(c){const a=items(c);let sec=document.getElementById('info-cards-section');if(!sec){sec=document.createElement('section');sec.id='info-cards-section';sec.className='section info-cards-section';sec.dir='rtl';sec.innerHTML='<div class="container"><div class="section-head info-cards-head"><span class="eyebrow">جامعہ کی معلومات</span><h2>اہم معلومات</h2><p>نیچے دیے گئے کسی بھی حصے پر کلک کریں اور اس کی تفصیلات ملاحظہ کریں۔</p></div><div class="info-cards-grid"></div></div>';const t=document.getElementById('taaruf');if(t)t.insertAdjacentElement('afterend',sec);else document.querySelector('main')?.prepend(sec)}
sec.querySelector('.info-cards-grid').innerHTML=a.map((x,i)=>`<button type="button" class="info-card" data-info-card="${i}"><span class="info-card-icon">${esc(x.icon)}</span><span class="info-card-title">${esc(x.title)}</span><span class="info-card-more">تفصیلات دیکھیں</span></button>`).join('');
if(!modal){modal=document.createElement('div');modal.id='info-card-modal';modal.className='info-card-modal';modal.innerHTML='<div class="info-card-backdrop"></div><div class="info-card-dialog" role="dialog" aria-modal="true" dir="rtl"><button type="button" class="info-card-close">×</button><div class="info-modal-icon"></div><h3></h3><div class="info-modal-body"></div></div>';document.body.appendChild(modal);modal.querySelector('.info-card-backdrop').onclick=()=>modal.classList.remove('open');modal.querySelector('.info-card-close').onclick=()=>modal.classList.remove('open')}
sec.querySelectorAll('[data-info-card]').forEach(b=>b.onclick=()=>show(a[+b.dataset.infoCard]||{}))}
async function save(sec){const {data:{user}}=await supabaseClient.auth.getUser();if(!user)throw Error('Admin session expired. Please login again.');const c=copy(await read());c.infoCards=defaults.map((d,i)=>({icon:(sec.querySelector(`[data-card="${i}.icon"]`)?.value??d.icon).trim(),title:(sec.querySelector(`[data-card="${i}.title"]`)?.value??d.title).trim(),body:(sec.querySelector(`[data-card="${i}.body"]`)?.value??d.body).trim()}));const {data,error}=await supabaseClient.from('site_settings').upsert({id:'homepage',content:c,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:'id'}).select('id').maybeSingle();if(error)throw error;if(!data)throw Error('Changes were not saved.');render(c)}
async function editor(){if(new URLSearchParams(location.search).get('admin')!=='1')return false;const tabs=document.querySelector('.ale-tabs'),forms=document.getElementById('ale-forms');if(!tabs||!forms)return false;let tab=tabs.querySelector('[data-tab="infoCards"]'),sec=forms.querySelector('[data-section="infoCards"]');if(!tab){tab=document.createElement('button');tab.type='button';tab.dataset.tab='infoCards';tab.textContent='اہم معلومات';tabs.appendChild(tab)}if(!sec){sec=document.createElement('section');sec.dataset.section='infoCards';sec.className='ale-section';sec.dir='rtl';sec.innerHTML='<div class="ale-media"><h3>اہم معلومات کے کارڈز</h3><p class="ale-note">یہ صرف public کے 8 cards ہیں۔ عنوان اور تفصیلات تبدیل کریں اور Save & Publish دبائیں۔</p>'+defaults.map((x,i)=>`<div class="ale-gallery-card"><h4>کارڈ ${i+1}</h4><div class="ale-field"><label>آئیکن</label><input data-card="${i}.icon"></div><div class="ale-field"><label>عنوان</label><input data-card="${i}.title"></div><div class="ale-field"><label>تفصیلات</label><textarea data-card="${i}.body" style="min-height:120px;line-height:2"></textarea></div></div>`).join('')+'<button id="public-info-save" type="button" style="width:100%;margin-top:14px;border:0;padding:12px;border-radius:9px;background:#176b3a;color:#fff;font-weight:800;cursor:pointer">اہم معلومات Save & Publish</button><div id="public-info-msg" style="margin-top:10px;font-weight:700"></div></div>';forms.appendChild(sec)}
async function fill(){const a=items(await read());a.forEach((x,i)=>{sec.querySelector(`[data-card="${i}.icon"]`).value=x.icon;sec.querySelector(`[data-card="${i}.title"]`).value=x.title;sec.querySelector(`[data-card="${i}.body"]`).value=x.body})}await fill();tab.onclick=async()=>{tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));forms.querySelectorAll('.ale-section').forEach(x=>x.classList.remove('active'));tab.classList.add('active');sec.classList.add('active');await fill()};const btn=sec.querySelector('#public-info-save');if(!btn.dataset.bound){btn.dataset.bound='1';btn.onclick=async()=>{const msg=sec.querySelector('#public-info-msg');try{btn.disabled=true;btn.textContent='Saving…';await save(sec);msg.textContent='Saved and published successfully.';msg.style.color='#176b3a';btn.textContent='Saved ✓';setTimeout(()=>{btn.disabled=false;btn.textContent='اہم معلومات Save & Publish'},1000)}catch(e){console.error(e);msg.textContent=e.message||'Save failed';msg.style.color='#a32121';btn.disabled=false;btn.textContent='اہم معلومات Save & Publish'}}}return true}
async function init(){css();try{render(await read())}catch(e){render({})}if(new URLSearchParams(location.search).get('admin')==='1'){let n=0;const t=setInterval(()=>{if(editor()||++n>100)clearInterval(t)},250)}else setInterval(async()=>{try{render(await read())}catch(e){}},3000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
