(()=>{
const defaults=[
 {icon:'📖',title:'نصابِ تعلیم',body:'یہاں نصابِ تعلیم، درجات اور متعلقہ تعلیمی معلومات درج کی جائیں گی۔'},
 {icon:'▣',title:'تعلیمی شعبہ جات',body:'یہاں جامعہ کے مختلف تعلیمی شعبہ جات کی تفصیل درج کی جائے گی۔'},
 {icon:'◈',title:'شعبہ جات',body:'یہاں جامعہ کے مختلف شعبہ جات اور ان کی بنیادی معلومات درج کی جائیں گی۔'},
 {icon:'☾',title:'دارالافتاء',body:'یہاں دارالافتاء سے متعلق تعارف، اوقات اور دیگر معلومات درج کی جائیں گی۔'},
 {icon:'⌂',title:'ادارہ و انتظامی معلومات',body:'یہاں ادارے، انتظامیہ اور متعلقہ معلومات درج کی جائیں گی۔'},
 {icon:'⌁',title:'منصوبے',body:'یہاں جاری اور آئندہ منصوبوں کی معلومات درج کی جائیں گی۔'},
 {icon:'☷',title:'قواعد و ضوابط',body:'یہاں طلبہ اور زائرین کے لیے ضروری قواعد و ضوابط درج کیے جائیں گے۔'},
 {icon:'▤',title:'نوٹس بورڈ',body:'اہم اعلانات، تازہ نوٹس اور انتظامیہ کی ضروری اطلاعات یہاں دکھائی جائیں گی۔'}
];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function load(){try{const {data,error}=await supabaseClient.from('site_settings').select('content').eq('id','homepage').maybeSingle();if(error)throw error;return data?.content||{}}catch(e){return {}}}
function render(c){
 if(document.getElementById('info-cards-section'))return;
 const items=Array.isArray(c.infoCards)&&c.infoCards.length?c.infoCards:defaults;
 const section=document.createElement('section');section.id='info-cards-section';section.className='section info-cards-section';section.dir='rtl';
 section.innerHTML='<div class="container"><div class="section-head info-cards-head"><span class="eyebrow">جامعہ کی معلومات</span><h2>اہم معلومات</h2><p>نیچے دیے گئے کسی بھی حصے پر کلک کریں اور اس کی تفصیلات ملاحظہ کریں۔</p></div><div class="info-cards-grid">'+items.slice(0,8).map((x,i)=>`<button type="button" class="info-card" data-info-card="${i}"><span class="info-card-icon">${esc(x.icon||defaults[i]?.icon||'•')}</span><span class="info-card-title">${esc(x.title||defaults[i]?.title||'معلومات')}</span><span class="info-card-more">تفصیلات دیکھیں</span></button>`).join('')+'</div></div>';
 const taaruf=document.getElementById('taaruf');if(taaruf)taaruf.insertAdjacentElement('afterend',section);else document.querySelector('main')?.prepend(section);
 const modal=document.createElement('div');modal.id='info-card-modal';modal.className='info-card-modal';modal.innerHTML='<div class="info-card-backdrop"></div><div class="info-card-dialog" role="dialog" aria-modal="true" dir="rtl"><button type="button" class="info-card-close" aria-label="Close">×</button><div class="info-modal-icon"></div><h3></h3><div class="info-modal-body"></div></div>';document.body.appendChild(modal);
 const close=()=>modal.classList.remove('open');modal.querySelector('.info-card-backdrop').onclick=close;modal.querySelector('.info-card-close').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
 section.querySelectorAll('[data-info-card]').forEach(btn=>btn.onclick=()=>{const x=items[Number(btn.dataset.infoCard)]||{};modal.querySelector('.info-modal-icon').textContent=x.icon||'•';modal.querySelector('h3').textContent=x.title||'معلومات';modal.querySelector('.info-modal-body').textContent=x.body||'';modal.classList.add('open')});
}
function css(){if(document.getElementById('info-cards-css'))return;const s=document.createElement('style');s.id='info-cards-css';s.textContent=`.info-cards-section{background:linear-gradient(180deg,#f7fbff,#eef5fb);padding-top:52px;padding-bottom:58px}.info-cards-head{text-align:center;margin-bottom:28px}.info-cards-head h2{color:#071b3a}.info-cards-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.info-card{min-height:205px;border:1px solid #dbe7f3;border-radius:18px;background:linear-gradient(145deg,#071b3a,#0b3764);color:#fff;padding:28px 18px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;cursor:pointer;box-shadow:0 14px 34px rgba(7,27,58,.12);transition:transform .2s,box-shadow .2s,background .2s}.info-card:hover{transform:translateY(-4px);box-shadow:0 20px 42px rgba(7,27,58,.2);background:linear-gradient(145deg,#0b3764,#0d4f86)}.info-card-icon{width:64px;height:64px;border-radius:16px;display:grid;place-items:center;background:rgba(255,255,255,.12);font-size:34px;margin-bottom:18px;color:#dceeff}.info-card-title{font-family:serif;font-size:24px;line-height:1.5;font-weight:700}.info-card-more{font-size:12px;color:#b9d7f2;margin-top:9px}.info-card-modal{position:fixed;inset:0;z-index:100000;display:none;align-items:center;justify-content:center;padding:20px}.info-card-modal.open{display:flex}.info-card-backdrop{position:absolute;inset:0;background:rgba(2,14,32,.7);backdrop-filter:blur(4px)}.info-card-dialog{position:relative;width:min(680px,94vw);max-height:82vh;overflow:auto;background:#fff;border-radius:22px;padding:34px;box-shadow:0 30px 90px rgba(0,0,0,.3);text-align:right}.info-card-close{position:absolute;left:16px;top:12px;border:0;background:#edf4fb;color:#071b3a;border-radius:50%;width:38px;height:38px;font-size:25px;cursor:pointer}.info-modal-icon{width:66px;height:66px;border-radius:16px;background:#071b3a;color:#fff;display:grid;place-items:center;font-size:34px;margin-bottom:16px}.info-card-dialog h3{font-family:serif;font-size:32px;color:#071b3a;margin:0 0 14px}.info-modal-body{font-family:serif;font-size:20px;line-height:2;color:#42536a;white-space:pre-line}@media(max-width:900px){.info-cards-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.info-cards-grid{grid-template-columns:1fr}.info-card{min-height:170px}.info-card-dialog{padding:26px 20px}.info-card-dialog h3{font-size:27px}.info-modal-body{font-size:18px}}`;document.head.appendChild(s)}
function addAdmin(){if(new URLSearchParams(location.search).get('admin')!=='1')return;const forms=document.getElementById('ale-forms'),tabs=document.querySelector('.ale-tabs');if(!forms||!tabs||tabs.querySelector('[data-tab="infoCards"]'))return;const b=document.createElement('button');b.type='button';b.dataset.tab='infoCards';b.textContent='اہم معلومات';tabs.appendChild(b);const section=document.createElement('section');section.dataset.section='infoCards';section.className='ale-section';section.dir='rtl';section.innerHTML='<div class="ale-media"><h3>اہم معلومات کے کارڈز</h3><p class="ale-note">ہر کارڈ کا عنوان اور مکمل معلومات آپ خود تبدیل کر سکتے ہیں۔ عوامی ویب سائٹ پر کارڈ پر کلک کرنے سے یہی معلومات سامنے آئیں گی۔</p>'+defaults.map((x,i)=>`<div class="ale-gallery-card"><h4>کارڈ ${i+1}</h4><div class="ale-field"><label>آئیکن</label><input data-path="infoCards.${i}.icon" dir="rtl"></div><div class="ale-field"><label>عنوان</label><input data-path="infoCards.${i}.title" dir="rtl"></div><div class="ale-field"><label>تفصیلات</label><textarea data-path="infoCards.${i}.body" dir="rtl" style="min-height:120px;line-height:2"></textarea></div></div>`).join('')+'</div>';forms.appendChild(section);const c=window.__siteContent||{};const arr=Array.isArray(c.infoCards)&&c.infoCards.length?c.infoCards:defaults;section.querySelectorAll('[data-path]').forEach(el=>{const p=el.dataset.path.split('.'),i=Number(p[1]),k=p[2];el.value=arr[i]?.[k]??defaults[i]?.[k]??''});b.onclick=()=>{tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));forms.querySelectorAll('.ale-section').forEach(x=>x.classList.remove('active'));b.classList.add('active');section.classList.add('active')};}
async function init(){css();const c=await load();render(c);if(new URLSearchParams(location.search).get('admin')==='1'){let n=0;const timer=setInterval(()=>{addAdmin();if(++n>80)clearInterval(timer)},250)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
