/* Limited public translator: ONLY Intro + the 8 About/Madrasa cards. */
(function(){'use strict';
var rtl=/[\u0590-\u08FF\uFB1D-\uFDFF\uFE70-\uFEFF]/;
function dir(el){if(!el)return;var v='value'in el?String(el.value||''):String(el.textContent||''),r=rtl.test(v);el.dir=r?'rtl':'ltr';el.style.direction=r?'rtl':'ltr';el.style.textAlign=r?'right':'left';el.setAttribute('lang',r?'ur':'en')}
function bind(){document.querySelectorAll('#taaruf input,#taaruf textarea,#taaruf [contenteditable="true"],#about .cards article input,#about .cards article textarea,#about .cards article [contenteditable="true"],#madrasa .program input,#madrasa .program textarea,#madrasa .program [contenteditable="true"]').forEach(function(e){if(e.dataset.dirBound)return;e.dataset.dirBound='1';dir(e);e.addEventListener('input',function(){dir(e)})})}
function markScope(){document.documentElement.setAttribute('translate','no');document.body.setAttribute('translate','no');document.querySelectorAll('#taaruf,#about .cards article,#madrasa .program').forEach(function(e){e.setAttribute('translate','yes')});var w=document.getElementById('google_translate_element');if(w)w.setAttribute('translate','no')}
function setupSearch(){var w=document.getElementById('google_translate_element');if(!w||document.getElementById('language-search'))return;var box=document.createElement('div');box.className='language-search-wrap';box.innerHTML='<label for="language-search">Language</label><input id="language-search" type="search" placeholder="Search language..." autocomplete="off"><div class="language-google-host"></div>';box.querySelector('.language-google-host').appendChild(w);var parent=document.querySelector('#taaruf .taaruf-card')||document.querySelector('#taaruf');if(parent)parent.appendChild(box);var input=box.querySelector('#language-search');input.addEventListener('input',function(){var q=input.value.toLowerCase().trim(),sel=box.querySelector('select.goog-te-combo');if(!sel)return;Array.from(sel.options).forEach(function(o){o.hidden=!!q&&o.textContent.toLowerCase().indexOf(q)<0})})}
window.googleTranslateElementInit=function(){if(!window.google||!google.translate)return;new google.translate.TranslateElement({pageLanguage:'en',includedLanguages:'af,ar,bn,zh-CN,zh-TW,cs,da,nl,en,fa,fi,fr,de,el,gu,ha,he,hi,hu,id,it,ja,ko,ms,ml,mr,ne,no,pl,pt,pa,ro,ru,sk,es,sv,ta,te,tr,uk,ur,vi,sw,yo',autoDisplay:false,layout:google.translate.TranslateElement.InlineLayout.SIMPLE},'google_translate_element');setTimeout(function(){var sel=document.querySelector('#google_translate_element select.goog-te-combo');if(sel){var opts=Array.from(sel.options),current=sel.value;opts.sort(function(a,b){return a.textContent.localeCompare(b.textContent,undefined,{sensitivity:'base'})});opts.forEach(function(o){sel.appendChild(o)});sel.value=current}setupSearch();markScope();bind()},1000)};
document.addEventListener('DOMContentLoaded',function(){markScope();bind();setupSearch();new MutationObserver(function(){markScope();bind();setupSearch()}).observe(document.documentElement,{childList:true,subtree:true})});
})();