(function(){
const defaults={brand:{name:'Darul Uloom Muhammadia',city:'Karachi',logo:'☪',phone:'0300 2778813',email:'bukharaoficial321@gmail.com',address:'Umar Megal Goth, Manghopir, Karachi',seo:'Darul Uloom Muhammadia Karachi — Qur\'anic Education, Islamic Studies, Hifz, Nazra and School Education in a disciplined environment.',heroImage:'',primary:'#0d47a1',accent:'#c8a45d'},nav:['About','Madrasa','School','Leadership','Gallery','Admissions','Student Portal','Contact','Admin Login'],hero:{eyebrow:'دارالعلوم محمدیہ کراچی',heading:'Knowledge with',highlight:'Faith & Character',description:'A place for Qur\'anic learning, Islamic education, character building and quality school education.',button:'Explore Madrasa',secondary:'Student Portal',cardTitle:'Qur\'anic Education',cardSubtitle:'Islamic Studies • Character Building • School Education'},stats:[['Qur\'anic','Learning'],['Islamic','Studies'],['School','Education'],['Values','Character Building']],about:{eyebrow:'ABOUT US',heading:'Education With Values',description:'Darul Uloom Muhammadia Karachi is dedicated to Qur\'anic education, Islamic learning, character building and quality education in a disciplined environment.',items:[['Our Mission','Promote beneficial knowledge and strong character.'],['Our Vision','Build a generation rooted in knowledge and values.'],['Islamic Values','Respect, discipline, honesty and responsibility.'],['Character Building','Education that develops both knowledge and conduct.']]},madrasa:{eyebrow:'MADRASA',heading:'Qur\'anic & Islamic Learning',items:[['Qaida','Basic Qur\'an reading, Arabic letters and correct pronunciation.'],['Nazra Qur\'an','Qur\'an recitation with proper pronunciation and Tajweed.'],['Hifz-ul-Qur\'an','Structured Qur\'an memorization and revision program.'],['Islamic Studies','Islamic knowledge, Seerah, Hadith, Fiqh and Arabic.']]},school:{eyebrow:'SCHOOL EDUCATION',heading:'Al Ameer Foundation School',description:'Quality school education in an Islamic environment, with a focus on academic development, discipline and character building.',classes:['Nursery','Prep','Class 1','Class 2','Class 3','Class 4','Class 5','Class 6','Class 7']},leadership:{eyebrow:'LEADERSHIP',heading:'Our Leadership',items:[['QB','Qari Muhammad Tayabb Bukhari Sahib','Founder'],['AH','Molana Ameer Hamza Bukhari Sahib','Principal']]},gallery:{eyebrow:'GALLERY',heading:'Campus & Activities',description:'Gallery content can be managed from the Admin Dashboard.',items:['Campus','Students','Events','Activities']},admissions:{eyebrow:'ADMISSIONS',heading:'Begin Your Learning Journey',description:'For secure application submission and status tracking, use the Student Portal.',notice:'Create a student account to submit an application and check its status anytime.',button:'Open Student Portal'},contact:{eyebrow:'CONTACT',heading:'Get in Touch',whatsapp:'WhatsApp',call:'Call Now',emailButton:'Email Us'},footer:{owner:'Umar Farooq'}};
function merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a;if(a&&typeof a==='object'){const o={...a};for(const k in b||{})o[k]=merge(a[k],b[k]);return o}return b??a}
function text(sel,value){const e=document.querySelector(sel);if(e&&value!=null)e.textContent=value}
function list(sel,items,fn){const es=document.querySelectorAll(sel);items.forEach((x,i)=>{if(es[i])fn(es[i],x,i)})}
function apply(c){
 document.title=c.brand.name+' '+c.brand.city;
 const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=c.brand.seo;
 text('.logo b',c.brand.name);text('.logo small',c.brand.city);text('.logo-mark',c.brand.logo);
 const topNav=document.querySelectorAll('nav a');c.nav.forEach((v,i)=>{if(topNav[i])topNav[i].textContent=v});
 text('.hero .eyebrow',c.hero.eyebrow);text('.hero h1',c.hero.heading);const h=document.querySelector('.hero h1');if(h){h.innerHTML='';h.append(document.createTextNode(c.hero.heading+' '));const sp=document.createElement('span');sp.textContent=c.hero.highlight;h.append(sp)}text('.hero-copy p',c.hero.description);text('.hero .actions .btn:not(.outline)',c.hero.button);text('.hero .actions .btn.outline',c.hero.secondary);text('.hero-card strong',c.hero.cardTitle);text('.hero-card span',c.hero.cardSubtitle);
 list('.stats-grid > div',c.stats,(e,x)=>{const b=e.querySelector('b'),s=e.querySelector('span');if(b)b.textContent=x[0];if(s)s.textContent=x[1]});
 text('#about .eyebrow',c.about.eyebrow);text('#about h2',c.about.heading);text('#about .section-head p',c.about.description);list('#about .cards article',c.about.items,(e,x,i)=>{textIn(e,'h3',x[0]);textIn(e,'p',x[1])});
 text('#madrasa .eyebrow',c.madrasa.eyebrow);text('#madrasa h2',c.madrasa.heading);list('#madrasa .program',c.madrasa.items,(e,x)=>{textIn(e,'h3',x[0]);textIn(e,'p',x[1])});
 text('#school .eyebrow',c.school.eyebrow);text('#school h2',c.school.heading);text('#school .split > div:first-child p',c.school.description);const cl=document.querySelector('.class-list');if(cl)cl.innerHTML=c.school.classes.map(x=>'<span>'+escapeHtml(x)+'</span>').join('');
 text('#leadership .eyebrow',c.leadership.eyebrow);text('#leadership h2',c.leadership.heading);list('#leadership .leaders article',c.leadership.items,(e,x)=>{textIn(e,'.avatar',x[0]);textIn(e,'h3',x[1]);textIn(e,'p',x[2])});
 text('#gallery .eyebrow',c.gallery.eyebrow);text('#gallery h2',c.gallery.heading);text('#gallery .section-head p',c.gallery.description);const g=document.querySelector('.gallery');if(g)g.innerHTML=c.gallery.items.map(x=>'<div>'+escapeHtml(x)+'</div>').join('');
 text('#admissions .eyebrow',c.admissions.eyebrow);text('#admissions h2',c.admissions.heading);text('#admissions .admission p',c.admissions.description);text('#admissions .notice',c.admissions.notice);text('#admissions .btn',c.admissions.button);
 text('#contact .eyebrow',c.contact.eyebrow);text('#contact h2',c.contact.heading);const cp=document.querySelectorAll('#contact .contact > div:first-child p');if(cp[0])cp[0].textContent=c.brand.address;if(cp[1])cp[1].innerHTML='<b>'+escapeHtml(c.brand.phone)+'</b>';if(cp[2])cp[2].textContent=c.brand.email;const ca=document.querySelectorAll('#contact .contact-actions a');if(ca[0])ca[0].textContent=c.contact.whatsapp;if(ca[1])ca[1].textContent=c.contact.call;if(ca[2])ca[2].textContent=c.contact.emailButton;
 const foot=document.querySelector('footer .footer');if(foot){const p=foot.querySelectorAll('p');if(p[1])p[1].textContent='Website Owner: '+c.footer.owner}
 let style=document.getElementById('cms-theme');if(!style){style=document.createElement('style');style.id='cms-theme';document.head.appendChild(style)}style.textContent=':root{--cms-primary:'+escapeCss(c.brand.primary)+';--cms-accent:'+escapeCss(c.brand.accent)+'}.btn{background:var(--cms-primary)!important}.hero{'+(c.brand.heroImage?'background-image:linear-gradient(90deg,rgba(4,19,41,.92),rgba(4,19,41,.55)),url("'+escapeCss(c.brand.heroImage)+'");background-size:cover;background-position:center;':'')+'}.logo-mark,.eyebrow,.hero h1 span{color:var(--cms-accent)!important}';
}
function textIn(e,sel,v){const x=e.querySelector(sel);if(x)x.textContent=v}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function escapeCss(s){return String(s??'').replace(/["\\]/g,'')}
async function init(){try{if(!window.supabaseClient)return;const {data,error}=await supabaseClient.from('site_settings').select('content').eq('id','homepage').maybeSingle();if(!error&&data&&data.content&&Object.keys(data.content).length)apply(merge(defaults,data.content))}catch(e){console.warn('CMS content unavailable',e)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();