(()=>{
const defaults={heading:'تعارف نامہ',body:'جامعہ کے تعارف اور بنیادی معلومات کے لیے یہاں اپنا متن درج کریں۔'};
async function load(){try{const {data,error}=await supabaseClient.from('site_settings').select('content').eq('id','homepage').maybeSingle();if(error)throw error;return data?.content||{}}catch(e){return {}}}
function rtl(el){if(!el)return;el.dir='rtl';el.style.direction='rtl';el.style.textAlign='right';el.setAttribute('lang','ur')}
function render(c){const box=document.getElementById('taaruf');if(!box)return;const t={...defaults,...(c.taaruf||{})};const h=box.querySelector('[data-taaruf-heading]'),p=box.querySelector('[data-taaruf-body]');if(h){h.textContent=t.heading||defaults.heading;rtl(h)}if(p){p.textContent=t.body||defaults.body;rtl(p)}}
function css(){if(document.getElementById('taaruf-css'))return;const s=document.createElement('style');s.id='taaruf-css';s.textContent=`#taaruf{direction:rtl!important;text-align:right!important;padding:56px 20px;background:linear-gradient(135deg,#f7fbff,#fffaf0)}#taaruf .taaruf-card{width:min(100%,900px);box-sizing:border-box;margin:0 auto;padding:42px 48px;background:#fff;border:1px solid #e3e8ef;border-radius:24px;box-shadow:0 14px 40px rgba(7,27,58,.10);text-align:right;direction:rtl}#taaruf .taaruf-card h2{margin:0 0 20px;text-align:center;direction:rtl;font-size:34px;line-height:1.5}#taaruf .taaruf-body{margin:0;text-align:right;direction:rtl;unicode-bidi:plaintext;white-space:pre-line;font-size:20px;line-height:2.15}#taaruf .taaruf-note{text-align:center}#taaruf .taaruf-card input,#taaruf .taaruf-card textarea,#taaruf .taaruf-card [contenteditable=true]{direction:rtl!important;text-align:right!important;unicode-bidi:plaintext}@media(max-width:700px){#taaruf{padding:30px 14px}#taaruf .taaruf-card{padding:28px 20px;border-radius:18px}#taaruf .taaruf-card h2{font-size:28px}#taaruf .taaruf-body{font-size:18px;line-height:2}}`;document.head.appendChild(s)}
function addAdminEditor(){if(new URLSearchParams(location.search).get('admin')!=='1')return;const forms=document.getElementById('ale-forms'),tabs=document.querySelector('.ale-tabs');if(!forms||!tabs||tabs.querySelector('[data-tab="taaruf"]'))return;const b=document.createElement('button');b.type='button';b.dataset.tab='taaruf';b.textContent='تعارف نامہ';tabs.insertBefore(b,tabs.querySelector('[data-tab="about"]')||tabs.firstChild);const section=document.createElement('section');section.dataset.section='taaruf';section.className='ale-section';section.dir='rtl';section.innerHTML='<div class="ale-media"><h3>تعارف نامہ</h3><p class="ale-note">یہ متن ہوم پیج پر تعارف نامہ کے حصے میں دکھایا جائے گا۔</p><div class="ale-field"><label>عنوان</label><input data-path="taaruf.heading" dir="rtl" lang="ur"></div><div class="ale-field"><label>تعارف کا متن</label><textarea data-path="taaruf.body" dir="rtl" lang="ur" style="min-height:220px;line-height:2;direction:rtl;text-align:right;unicode-bidi:plaintext"></textarea></div></div>';forms.appendChild(section);const c=window.__siteContent||{};section.querySelector('[data-path="taaruf.heading"]').value=c.taaruf?.heading||defaults.heading;section.querySelector('[data-path="taaruf.body"]').value=c.taaruf?.body||defaults.body;b.onclick=()=>{tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));forms.querySelectorAll('.ale-section').forEach(x=>x.classList.remove('active'));b.classList.add('active');section.classList.add('active')}}
async function init(){css();const c=await load();render(c);if(new URLSearchParams(location.search).get('admin')==='1'){let n=0;const timer=setInterval(()=>{addAdminEditor();if(++n>80)clearInterval(timer)},250)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();