(()=>{
const defaults={heading:'تعارف نامہ',body:'جامعہ کے تعارف اور بنیادی معلومات کے لیے یہاں اپنا متن درج کریں۔'};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function load(){try{const {data,error}=await supabaseClient.from('site_settings').select('content').eq('id','homepage').maybeSingle();if(error)throw error;return data?.content||{}}catch(e){return {}}}
function render(c){const box=document.getElementById('taaruf');if(!box)return;const t={...defaults,...(c.taaruf||{})};const h=box.querySelector('[data-taaruf-heading]'),p=box.querySelector('[data-taaruf-body]');if(h)h.textContent=t.heading||defaults.heading;if(p)p.textContent=t.body||defaults.body}
function css(){if(document.getElementById('taaruf-css'))return;const s=document.createElement('style');s.id='taaruf-css';s.textContent=`#taaruf{direction:rtl;text-align:right;background:linear-gradient(135deg,#fffaf0,#f7fbff);border-top:1px solid #eadfbf;border-bottom:1px solid #dfe8f3}.taaruf-card{max-width:1050px;margin:auto;background:#fff;border:1px solid #e6dfcc;border-radius:22px;padding:34px 38px;box-shadow:0 16px 45px rgba(7,27,58,.08)}.taaruf-card .eyebrow{display:block;text-align:right}.taaruf-card h2{font-family:serif;font-size:36px;line-height:1.5;margin:4px 0 16px;color:#071b3a}.taaruf-body{font-family:serif;font-size:21px;line-height:2.2;color:#33455f;white-space:pre-line}.taaruf-note{font-size:12px;color:#7b8798;margin-top:16px}@media(max-width:700px){.taaruf-card{padding:24px 18px;border-radius:16px}.taaruf-card h2{font-size:29px}.taaruf-body{font-size:18px;line-height:2}}` ;document.head.appendChild(s)}
function addAdminEditor(){if(new URLSearchParams(location.search).get('admin')!=='1')return;const forms=document.getElementById('ale-forms'),tabs=document.querySelector('.ale-tabs');if(!forms||!tabs||tabs.querySelector('[data-tab="taaruf"]'))return;const b=document.createElement('button');b.type='button';b.dataset.tab='taaruf';b.textContent='تعارف نامہ';tabs.insertBefore(b,tabs.querySelector('[data-tab="about"]')||tabs.firstChild);const section=document.createElement('section');section.dataset.section='taaruf';section.className='ale-section';section.dir='rtl';section.innerHTML='<div class="ale-media"><h3>تعارف نامہ</h3><p class="ale-note">یہ متن ہوم پیج پر تعارف نامہ کے حصے میں دکھایا جائے گا۔ آپ اسے مکمل طور پر اپنی مرضی سے تبدیل کر سکتے ہیں۔</p><div class="ale-field"><label>عنوان</label><input data-path="taaruf.heading" dir="rtl"></div><div class="ale-field"><label>تعارف کا متن</label><textarea data-path="taaruf.body" dir="rtl" style="min-height:220px;line-height:2"></textarea></div></div>';forms.appendChild(section);const c=window.__siteContent||{};section.querySelector('[data-path="taaruf.heading"]').value=c.taaruf?.heading||defaults.heading;section.querySelector('[data-path="taaruf.body"]').value=c.taaruf?.body||defaults.body;b.onclick=()=>{tabs.querySelectorAll('button').forEach(x=>x.classList.remove('active'));forms.querySelectorAll('.ale-section').forEach(x=>x.classList.remove('active'));b.classList.add('active');section.classList.add('active')};}
async function init(){css();const c=await load();render(c);if(new URLSearchParams(location.search).get('admin')==='1'){let n=0;const timer=setInterval(()=>{addAdminEditor();if(++n>80)clearInterval(timer)},250)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
